# Workflow: PR Review Pipeline for squadron-dev
#
# Triggers on PRs targeting the squadron-dev branch.
# Sequential pipeline:
#   1. test-coverage agent reviews test adequacy → approves
#   2. security-review agent checks for vulnerabilities → approves
#   3. pr-review agent does final review, approves, and merges
#
# Each stage advances only when the previous stage's agent approves.
# Any rejection stops the pipeline.

name: squadron-dev-pr-pipeline
description: >
  Sequential review pipeline for PRs targeting squadron-dev.
  Test coverage → security review → final review & merge.

trigger:
  event: pull_request.opened
  conditions:
    base_branch: squadron-dev

stages:
  - name: test-coverage
    agent: test-coverage
    action: review
    on_approve: next
    on_reject: stop

  - name: security-review
    agent: security-review
    action: review
    on_approve: next
    on_reject: stop

  - name: final-review
    agent: pr-review
    action: review_and_merge
    on_approve: complete
    on_reject: stop
